package com.joysistvi.ecommerce.model;

/**
 * Report represents a sales analytics report entity generated by admins.
 */
public class Report {
    private int id;
    private int admin_id;
    private String type;
    private String date;
    private double sales;
    private int orders;
    private String notes;

    // Full constructor initializing report entity fields.
    public Report(int id, int admin_id, String type, String date, double sales, int orders, String notes) {
        this.id = id;
        this.admin_id = admin_id;
        this.type = type;
        this.date = date;
        this.sales = sales;
        this.orders = orders;
        this.notes = notes;
    }

    // Constructor initializing report entity fields without ID.
    public Report(int adminId, String type, String date, double sales, int orders, String notes) {
        this.admin_id = adminId;
        this.type = type;
        this.date = date;
        this.sales = sales;
        this.orders = orders;
        this.notes = notes;
    }

    // Returns report ID.
    public int getId() {
        return id;
    }

    // Sets report ID.
    public void setId(int id) {
        this.id = id;
    }

    // Returns admin ID.
    public int getAdmin_id() {
        return admin_id;
    }

    // Sets admin ID.
    public void setAdmin_id(int admin_id) {
        this.admin_id = admin_id;
    }

    // Returns report type string.
    public String getType() {
        return type;
    }

    // Sets report type string.
    public void setType(String type) {
        this.type = type;
    }

    // Returns report date string.
    public String getDate() {
        return date;
    }

    // Sets report date string.
    public void setDate(String date) {
        this.date = date;
    }

    // Returns total sales amount.
    public double getSales() {
        return sales;
    }

    // Sets total sales amount.
    public void setSales(double sales) {
        this.sales = sales;
    }

    // Returns total order count.
    public int getOrders() {
        return orders;
    }

    // Sets total order count.
    public void setOrders(int orders) {
        this.orders = orders;
    }

    // Returns report notes string.
    public String getNotes() {
        return notes;
    }

    // Sets report notes string.
    public void setNotes(String notes) {
        this.notes = notes;
    }
}
